### PR TITLE
Fix issue with broken install when using existing config.json

### LINKED ISSUE #2055: error when re-using config file
## Expected Behaviour

running `node install` with an existing config file should populate the config with the existing `config.json`

## Actual Behaviour

The script fails to execute, with the following behaviour:

```
node install

Found an existing config.json file. Do you want to use the values in this file during install?
> Use existing config values? y/N (N) y

This script will install the application. Please wait ...

Now setting configuration items.
> Database server user
> Database server password
Now configuring the master tenant.

\ Starting server
/opt/adapt_authoring/node_modules/nodemailer/lib/mailer/index.js:45
        this.transporter.mailer = this;
                                ^

TypeError: Cannot create property 'mailer' on string ''
    at new Mail (/opt/adapt_authoring/node_modules/nodemailer/lib/mailer/index.js:45:33)
    at Object.module.exports.createTransport (/opt/adapt_authoring/node_modules/nodemailer/lib/nodemailer.js:58:14)
    at new Mailer (/opt/adapt_authoring/lib/mailer.js:57:33)
    at Origin.<anonymous> (/opt/adapt_authoring/lib/application.js:461:18)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Origin.emit (events.js:211:7)
    at Origin.<anonymous> (/opt/adapt_authoring/lib/application.js:227:10)
    at emitNone (events.js:106:13)
    at Origin.emit (events.js:208:7)
    at Origin.<anonymous> (/opt/adapt_authoring/lib/application.js:215:12)
    at emitOne (events.js:121:20)
    at Origin.emit (events.js:211:7)
    at Origin.<anonymous> (/opt/adapt_authoring/lib/application.js:173:16)
    at Array.some (<anonymous>)
    at Origin.modulePreloadEventHandler (/opt/adapt_authoring/lib/application.js:162:24)
    at emitTwo (events.js:126:13)
    at Origin.ModulePreloader.emit (events.js:214:7)
    at Origin.ModulePreloader.moduleLoaded (/opt/adapt_authoring/lib/tenantmanager.js:223:21)
    at emitOne (events.js:121:20)
    at Origin.emit (events.js:211:7)
    at Origin.<anonymous> (/opt/adapt_authoring/lib/application.js:173:16)
```

## Steps to Reproduce
1. use `node-install` to install adapt_authoring
2. values in my case were close to default, apart from using my own SMTP server.  NB, the SMTP user password contains some punctuation characters - perhaps this is not properly parsed?  Also, I did not use an SMTP URL, values were entered via the install script dialogues.
3. run `node-install` again and it fails

## Versions
  - Authoring Tool Version: v2.2.5 (latest github) 
  - Framework Version: v2.2.5 (latest github) 
  - Server Operating System: Debian 9
  - Browser: Firefox

### PR DESCRIPTION
**Pull request by taylortom**
Also includes:
- General amends to code style
- Underscore methods replaced with ES6 equivalents

Fixes #2055.

### CODE REVIEW

File: install.js [hunk 1]
```diff
@@ -537,29 +532,27 @@ function saveConfig(configItems, callback) {
...
     dbType: 'mongoose',
     auth: 'local',
     root: process.cwd()
   };
   // copy over the input values
-  _.each(configItems, function(value, key) {
-    config[key] = value;
-  });
-  
+  Object.keys(configItems).forEach(key => config[key] = configItems[key]);
```
Comment (tomgreenfield) [inline install.js]: My only comment would be that you said it might read better with an `Object.assign()`.
