### PR TITLE
Fix to old asset not being able to remove themselves

### LINKED ISSUE #713: Remove asset button does not work with old asset links
This is because the model doesn't save when the course asset is not found.

### PR DESCRIPTION
**Pull request by darylhedley**
fixes #713

### CODE REVIEW

File: frontend/src/core/scaffold/views/scaffoldAssetView.js [hunk 1]
```diff
@@ -255,6 +255,9 @@ define(function(require) {
                         console.log('error', error);
```
Comment (dennis-learningpool) [inline frontend/src/core/scaffold/views/scaffoldAssetView.js]: do we still remove `console.log`s when we find them?

**Comment by dennis-learningpool** [comment]
+1

**Comment by brian-learningpool** [comment]
+1
