### PR TITLE
do not create thumbnails for svg's

### LINKED ISSUE #2065: Import of course with SVG asset into AT 0.5.0 seems to yield an error
## Expected Behaviour
I import an exported course, containig an SVG asset, and I expected it to show up in the asset library.

## Actual Behaviour
The import fails with the error message;
`Failed to create image thumbnail: ffmpeg exited with code 1: /root/adapt_authoring/data/master/assets/46/af/46af89e59240177046a12a779a418289f4a7731e.svg: Invalid data found when processing input`

## Steps to Reproduce
1. Export a course with an SVG asset from an AT.
1. Import the course into AT 0.5.0.

## Versions
  - Authoring Tool Version: 0.5.0
  - Framework Version: 2.2.5
  - Node.js Version: 8.11.4
  - MongoDB Version; 4.0.2
  - Operating System: Ubuntu 16.04.5 (AT server)
  - Browser: Chrome, Win10

### PR DESCRIPTION
**Pull request by lc-thomasberger**
fixes #2065 

This is a temporary solution and should be removed once we a soultion for https://github.com/adaptlearning/adapt_authoring/issues/1860

### CODE REVIEW

File: plugins/filestorage/localfs/index.js [hunk 1]
```diff
@@ -356,6 +356,10 @@ LocalFileStorage.prototype.createThumbnail = function (filePath, fileType, optio
   }
   var fileFormat = fileType.split('/')[1];
   fileType = fileType.split('/')[0];
+  // https://github.com/adaptlearning/adapt_authoring/issues/2065
+  if (fileFormat === 'svg+xml') {
```
Comment (taylortom) [inline plugins/filestorage/localfs/index.js]: Can we get this check moved into the [isThumbnailTypeSupported](https://github.com/adaptlearning/adapt_authoring/blob/5cfae7a0ba0c0bccaa72fd719b71ff9271b31e8c/plugins/filestorage/localfs/index.js#L405-L414) method?

File: plugins/filestorage/localfs/index.js [hunk 2]
```diff
@@ -402,11 +398,12 @@ LocalFileStorage.prototype.createThumbnail = function (filePath, fileType, optio
...
 
-function isThumbnailTypeSupported(type) {
+function isThumbnailTypeSupported(type, format) {
   switch(type) {
     case 'video':
     case 'image':
-      return true;
+      // https://github.com/adaptlearning/adapt_authoring/issues/2065
+      return format !== 'svg+xml';
       break;
```
Comment (tomgreenfield) [inline plugins/filestorage/localfs/index.js]: Please remove `break`.
