### PR TITLE
Sort plugins alphabetically on pluginManagement pages

### LINKED ISSUE #2145: Plugins should be sorted alphabetically in plugin management
## Expected Behaviour
When I view the plugin management pages the plugins should be sorted alphabetically.

## Actual Behaviour
Plugins are not sorted alphabetically

## Steps to Reproduce
1. Navigate to plugin mangement
1. View any of themes, menus, extensions or components and see the plugins are not ordered

## Versions
  - Authoring Tool Version: 0.6.1

### PR DESCRIPTION
**Pull request by canstudios-nicolaw**
Fixes #2145 

To test go to the plugin management area and view the pages, all components/extensions/themes/menus are now sorted alphabetically.

### CODE REVIEW

File: frontend/src/modules/editor/global/editorDataLoader.js [hunk 1]
```diff
@@ -204,7 +204,7 @@ define(function(require) {
       model: Model,
       url: url,
       _type: siblingTypes || inferredType
-    });
+    }).sortByField('displayName');
```
Comment (tomgreenfield) [inline frontend/src/modules/editor/global/editorDataLoader.js]: Suggest instead just passing in the option `comparator: 'displayName'`?
