### PR TITLE
Fixes #2178

### LINKED ISSUE #2178: Cannot fully import courses with submenus
## Expected Behaviour
When importing a course that has a sub menu all valid content should be imported.

## Actual Behaviour
AT gives error warning of orphaned content and does not import sub menu contentObjects and their children ABC's. 

## Steps to Reproduce
1. Export a course with a submenu that contains a page with valid content e.g. one page, article, block and text component.
2. Re-import the course.
3. Import displays partial course import error, e.g.

> The following elements could not be imported:
> contentobject's: 5c3372f6c106a20de260c093
> article's: 5c3372f6c106a20de260c094
> block's: 5c3372f6c106a20de260c095
> component's: 5c337311c106a20de260c096
> Please check your imported Course. 

ID's correspond to valid page and article, block, component contained in the submenu.

## Versions
  - Authoring Tool Version: master branch
  - Framework Version: n/a
  - Node.js Version: v8.12.0
  - MongoDB Version: v3.6.0
  - Operating System: n/a
  - Browser: n/a

### PR DESCRIPTION
**Pull request by canstudios-nicolaw**
Fixes issue #2178 which was introduced in https://github.com/adaptlearning/adapt_authoring/pull/2109/files.

To test, create a course with a page and a submenu that contains a valid page (has an article/block/component) and export and re-import the course. The course should import successfully.

### CODE REVIEW

File: plugins/output/adapt/importsource.js [hunk 1]
```diff
@@ -409,14 +409,14 @@ function ImportSource(req, done) {
...
+            case 'contentobject': { // Sorts in-place the content objects to make sure processing can happen
+              var byParent = _.groupBy(contentJson, '_parentId');
               Object.keys(byParent).forEach(id => {
                 byParent[id].forEach((item, index) => item._sortOrder = index + 1);
               });
-              var groups = _.groupBy(data, '_type');
+              var groups = _.groupBy(contentJson, '_type');
               var sortedSections = helpers.sortContentObjects(groups.menu, origCourseId, []);
-              data = sortedSections.concat(groups.page);
+                  contentJson = sortedSections.concat(groups.page);
```
Comment (tomgreenfield) [inline plugins/output/adapt/importsource.js]: Please revert indentation.
