### PR TITLE
Fix dashboard infinite scrolling/pagination

### LINKED ISSUE #2253: Dashboard paging broken after deleting courses
## Expected Behaviour
On deleting a course, we need to do a fresh fetch to make sure the full amount of courses are shown. 

## Actual Behaviour
It's possible to break the paging by deleting enough courses to hide the scrollbar.

## Steps to Reproduce
1. Make sure you have enough courses to cause paging
1. Resize browser to fit a small number of courses (I had two rows of three)
1. Delete courses until you're down to a single row
1. Note no more courses are fetched, page must be refreshed to fix

### PR DESCRIPTION
**Pull request by taylortom**
Fixes #2253

### CODE REVIEW

File: frontend/src/modules/projects/views/projectView.js [hunk 1]
```diff
@@ -97,7 +97,10 @@ define(function(require) {
 
     deleteProject: function(event) {
       this.model.destroy({
-        success: _.bind(this.remove, this),
+        success: _.bind(function() {
+          Origin.trigger('dashboard:refresh');
+          this.remove();
+        }, this),
```
Comment (canstudios-nicolaw) [inline frontend/src/modules/projects/views/projectView.js]: Please can you switch to native bind?

Comment (taylortom) [reply frontend/src/modules/projects/views/projectView.js]: 👍 have also updated all other uses of `_.bind` in the file.
