### PR TITLE
Fix for trying to access course that does not exists looks like I have no course

### LINKED ISSUE #2351: Trying to access course that does not exists looks like I have no course
## Expected Behaviour
Trying to go to a course that does not exists, error should be shown and redirected back to dashboard.

## Actual Behaviour
Error is shown and after clicking 'Ok' empty dashboard is shown.

## Steps to Reproduce
1. Go to any course
1. Copy url of a course
1. Paste url in new tab and change one letter/number to different (If url is: example.com/#editor/5ce67923a5783767fa65414**0**/menu change to: example.com/#editor/5ce67923a5783767fa65414**1**/menu)

Or
1. Go to <server>/#editor

## Versions
  - Authoring Tool Version: v0.8.0
  - Framework Version: v2.4.0
  - Browser: Chrome

### PR DESCRIPTION
**Pull request by canstudios-simonasd**
Fixes #2351

### CODE REVIEW

File: frontend/src/modules/editor/global/editorDataLoader.js [hunk 1]
```diff
@@ -109,9 +112,15 @@ define(function(require) {
...
           Origin.off('editor:dataLoaded', done);
+          Origin.off('editor:failedToLoad', removeEvents);
           callback.apply(this);
         }
-      }
+      };
+      var removeEvents = function() {
+        Origin.off('editor:dataPreloaded', done);
+        Origin.off('editor:dataLoaded', done);
+        Origin.off('editor:failedToLoad', removeEvents);
```
Comment (tomgreenfield) [inline frontend/src/modules/editor/global/editorDataLoader.js]: Suggest the object-style syntax:
```js
Origin.off({
  'editor:dataPreloaded editor:dataLoaded': done,
  'editor:failedToLoad': removeEvents
});
```

File: frontend/src/modules/editor/global/editorDataLoader.js [hunk 2]
```diff
@@ -107,11 +110,21 @@ define(function(require) {
     waitForLoad: function(callback) {
       var done = function() {
         if(preloader.hasLoadedData()) {
-          Origin.off('editor:dataPreloaded', done);
-          Origin.off('editor:dataLoaded', done);
+          Origin.off({
```
Comment (tomgreenfield) [inline frontend/src/modules/editor/global/editorDataLoader.js]: Just noticed this; is there any reason for the duplicate code here and on lines 122–126? Could there just be a call to `removeEvents()`?
